camera_name: cascade/milestone_universal_camera
frame_id: cascade/milestone_universal_camera/camera_link
settings:
  framerate: 1
  manual_acquisition: False
uri:
  ip: "192.168.1.20"
  protocol: "rtsp"
  port: "554"
  username: "kapernikov"
  password: "Pieter123"
  suffix: "/live/82C51260-DFC2-4A14-888B-27688FC9D825"
  device_index: 0
