int8 MOVE_HOME=0
int8 MOVE_NEXT=1
int8 MOVE_PREVIOUS=-1
int8 MOVE_FIRST=2
int8 MOVE_LAST=-2
int8 MOVE_SAME=3
int8 goal
---
bool result
smelter_msgs/PanTiltZoom ptz
duration elapsed_time
---
smelter_msgs/PanTiltZoom ptz
duration elapsed_time
